---
sudo: required
services:
  - docker
language: generic
env:
  - OPTIONS=--vim-80-only
  - OPTIONS=--vim-81-only
  - OPTIONS=--neovim-03-only
  - OPTIONS=--linter-only
script: |
  ./run-tests -v $OPTIONS
