name: Release
on:
  release:
    types: [created]

jobs:
  build_and_upload_assets:
    name: Build and upload binary assets
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - node-version: 14
          - os: macos-latest
            target: macos
            asset-name: vim-doge-macos.tar.gz
            asset-path: ./bin/vim-doge-macos.tar.gz
          - os: ubuntu-latest
            target: linux
            asset-name: vim-doge-linux.tar.gz
            asset-path: ./bin/vim-doge-linux.tar.gz
    runs-on : ${{ matrix.os }}
    steps:
      - name: Checkout kkoomen/vim-doge
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --no-save
      - name: Build binary
        run: npm run build:binary -- node${{ matrix.node-version }}-${{ matrix.target }}-x64 vim-doge-${{ matrix.target }}
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset-path: ${{ matrix.asset-path }}
          asset-name: ${{ matrix.asset-name }}
          asset_content_type: application/zip
