name: release
on:
  release:
    types: [created]

jobs:
  build_and_upload_assets:
    needs: [create_release]
    name: Build and upload binary assets
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on : ${{ matrix.os }}
    env:
      NODE_VERSION: 14
      TARGET: $(echo $RUNNER_OS | tr '[:upper:]' '[:lower:]')
      ASSET_FILENAME: vim-doge-$(echo $RUNNER_OS | tr '[:upper:]' '[:lower:]')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install
      - name: Build binary
        run: npm run build:binary -- node${{ env.NODE_VERSION }}-${{ env.TARGET }}-x64 ${{ env.ASSET_FILENAME }}
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Get release upload url
        id: asset_info
        run: |
          echo ::set-output name=asset_path::./bin/${{ env.ASSET_FILENAME }}.tar.gz
          echo ::set-output name=asset_name::${{ env.ASSET_FILENAME }}.tar.gz
      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.asset_info.outputs.asset_path }}
          asset_name: ${{ steps.asset_info.outputs.asset_name }}
          asset_content_type: application/zip
