name: tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  tests_vim:
    name: Tests (Vim)
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        vim-version: [v7.4.2119, stable]
        node-version: [10, 12, 14]
    runs-on: ${{ matrix.os }}
    env:
      TARGET: $(echo $RUNNER_OS | tr '[:upper:]' '[:lower:]')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci --no-save
      - name: Build binary
        run: npm run build:binary -- node${{ matrix.node-version }}-${{ env.TARGET }}-x64
      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: ${{ matrix.vim-version }}
          neovim: false
      - name: Run tests
        run: ./scripts/run-vader-tests.sh "${{ steps.vim.outputs.executable }}"

  vint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install vim-vint
      - run: vint -s ./autoload ./plugin
