name: Tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  tests_vim:
    name: Tests (Vim)
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        vim-version: [v7.4.2119, head]
        node-version: [10, 12, 14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get build info
        id: build_info
        run: |
          echo ::set-output name=target::$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')
      - name: Checkout kkoomen/vim-doge
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout junegunn/vader.vim
        uses: actions/checkout@v2
        with:
          repository: junegunn/vader.vim
          path: vader
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --no-save
      - name: Build binary
        run: npm run build:binary -- node${{ matrix.node-version }}-${{ steps.build_info.outputs.target }}-x64
      - name: Setup Vim
        uses: thinca/action-setup-vim@v1
        id: vim
        with:
          vim_version: ${{ matrix.vim-version }}
          vim_type: vim
      - name: Run tests
        run: ./scripts/run-vader-tests.sh "${{ steps.vim.outputs.executable }}"

  tests_neovim:
    name: Tests (NeoVim)
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        vim-version: [v0.3.2, head]
        node-version: [10, 12, 14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get build info
        id: build_info
        run: |
          echo ::set-output name=target::$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')
      - name: Checkout kkoomen/vim-doge
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout junegunn/vader.vim
        uses: actions/checkout@v2
        with:
          repository: junegunn/vader.vim
          path: vader
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --no-save
      - name: Build binary
        run: npm run build:binary -- node${{ matrix.node-version }}-${{ steps.build_info.outputs.target }}-x64
      - name: Setup Vim
        uses: thinca/action-setup-vim@v1
        id: vim
        with:
          vim_version: ${{ matrix.vim-version }}
          vim_type: neovim
      - name: Run tests
        run: ./scripts/run-vader-tests.sh "${{ steps.vim.outputs.executable }}"

  vint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install vim-vint
      - run: vint -s ./autoload ./plugin
